;;; package --- Summary
;;; Commentary:
;;; Code:
(add-to-list 'auto-mode-alist '("\\.org\\'". org-mode))
(add-to-list 'auto-mode-alist '("\\.php$". php-mode))
(add-to-list 'auto-mode-alist '("\\.sql$". sql-mode))
(add-to-list 'auto-mode-alist '("\\.tpl$". smarty-mode))
(add-to-list 'auto-mode-alist '("\\.el$". emacs-lisp-mode))
(add-to-list 'auto-mode-alist '("\\.\\(?:yml\\|yaml\\)$". yaml-mode))
(add-to-list 'auto-mode-alist '("\\.js$". js2-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . js2-jsx-mode))
(add-to-list 'auto-mode-alist '("\\.json$". json-mode))
(add-to-list 'auto-mode-alist '("\\.styl$'". sws-mode))
(add-to-list 'auto-mode-alist '("\\.jade$'". jade-mode))
(add-to-list 'auto-mode-alist '("\\.coffee$". coffee-mode))
(add-to-list 'auto-mode-alist '("\\.md$". markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown$".	markdown-mode))
(add-to-list 'auto-mode-alist '("\\.text$". markdown-mode))
(add-to-list 'auto-mode-alist '("\\.html\\.erb$". web-mode))
(add-to-list 'auto-mode-alist '("\\.html$". web-mode))
(add-to-list 'auto-mode-alist '("\\.scss$". scss-mode))
(add-to-list 'auto-mode-alist '("\\.sass$". sass-mode))
(add-to-list 'auto-mode-alist '("\\.[rR]\\'". R-mode))
(add-to-list 'auto-mode-alist '("\\.[Cc][Ss][Vv]\\'". csv-mode))
(add-to-list 'auto-mode-alist '("\\.slim\\'". slim-mode))
(add-to-list 'auto-mode-alist
	     '("\\.\\(?:gemspec\\|irbrc\\|gemrc\\|rake\\|rb\\|ru\\|thor\\)\\'" . ruby-mode))
(add-to-list 'auto-mode-alist
	     '("\\(Capfile\\|Gemfile\\|[rR]akefile\\)\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.cs\\'". csharp-mode))
